<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\bosses.eu.json" LogicalName="BdoTimers.Core.Data.bosses.eu.json" WithCulture="false" />
  </ItemGroup>

</Project>
